require('dotenv').config();
const mongoose = require('mongoose');

const connectDB = async () => {
  const conn = await mongoose.connect(process.env.MONGO_URI);
  console.log('MongoDB Connected:', conn.connection.host);
};

// University Schema
const UniversitySchema = new mongoose.Schema({
  name: String,
  city: String,
  keys: [String],
  fact: String,
  links: [{
    label: String,
    url: String,
    desc: String,
  }],
});

// Country Schema
const CountrySchema = new mongoose.Schema({
  key: String,
  flag: String,
  fact: String,
  embassy: {
    name: String,
    url: String,
  },
  orgs: [{
    name: String,
    url: String,
  }],
});

const University = mongoose.model('University', UniversitySchema);
const Country = mongoose.model('Country', CountrySchema);

const universities = [
  { keys: ['st mary','stmary','twickenham'], name: "St Mary's University, Twickenham", city: 'London', fact: "St Mary's is one of the safest and most welcoming campuses in London with a tight knit community feel.", links: [{ label: 'Student Union', url: 'https://www.stmarys.ac.uk/student-union', desc: 'Support and representation' }, { label: 'Student Wellbeing', url: 'https://www.stmarys.ac.uk/student-life/wellbeing', desc: 'Free mental health support' }, { label: 'Careers Centre', url: 'https://www.stmarys.ac.uk/careers', desc: 'Jobs and CV help' }] },
  { keys: ['ucl','university college london'], name: 'University College London', city: 'London', fact: 'UCL is consistently ranked in the top 10 universities in the world.', links: [{ label: 'Students Union UCL', url: 'https://studentsunionucl.org', desc: 'Student support and societies' }, { label: 'Student Wellbeing', url: 'https://www.ucl.ac.uk/students/support-and-wellbeing', desc: 'Mental health and counselling' }, { label: 'Careers Service', url: 'https://www.ucl.ac.uk/careers', desc: 'Career guidance' }] },
  { keys: ["king's",'kings college','kcl'], name: "King's College London", city: 'London', fact: "King's is one of the world's leading research universities along the River Thames.", links: [{ label: 'KCLSU', url: 'https://www.kclsu.org', desc: 'Student union and support' }, { label: 'Counselling', url: 'https://www.kcl.ac.uk/campuslife/services/counselling', desc: 'Free counselling services' }] },
  { keys: ['imperial'], name: 'Imperial College London', city: 'London', fact: 'Imperial is one of the top science and engineering universities in the world.', links: [{ label: 'Imperial College Union', url: 'https://www.imperialcollegeunion.org', desc: 'Student union and welfare' }, { label: 'Student Wellbeing', url: 'https://www.imperial.ac.uk/students/health-and-wellbeing/', desc: 'Mental health and counselling' }] },
  { keys: ['lse','london school of economics'], name: 'London School of Economics', city: 'London', fact: 'The LSE is arguably the most influential social science university in the world.', links: [{ label: 'LSE Students Union', url: 'https://www.lsesu.com', desc: 'Student union and support' }, { label: 'Student Wellbeing', url: 'https://info.lse.ac.uk/current-students/student-wellbeing', desc: 'Counselling and mental health' }] },
  { keys: ['oxford'], name: 'University of Oxford', city: 'Oxford', fact: 'Oxford is the oldest university in the English speaking world and consistently ranked the best.', links: [{ label: 'Oxford Students Union', url: 'https://www.oxfordsu.org', desc: 'Student union and welfare' }, { label: 'Student Welfare', url: 'https://www.ox.ac.uk/students/welfare', desc: 'Counselling and welfare support' }, { label: 'Careers Service', url: 'https://www.careers.ox.ac.uk', desc: 'Career guidance' }] },
  { keys: ['cambridge'], name: 'University of Cambridge', city: 'Cambridge', fact: 'Cambridge is one of the greatest universities in human history.', links: [{ label: 'Cambridge SU', url: 'https://www.cambridgesu.co.uk', desc: 'Student union and welfare' }, { label: 'Student Counselling', url: 'https://www.counselling.cam.ac.uk', desc: 'Free counselling and mental health' }, { label: 'Careers Service', url: 'https://www.careers.cam.ac.uk', desc: 'Career guidance' }] },
  { keys: ['manchester'], name: 'University of Manchester', city: 'Manchester', fact: 'Manchester is a Russell Group powerhouse where the atom was first split.', links: [{ label: 'Manchester Students Union', url: 'https://manchesterstudentsunion.com', desc: 'Student union and support' }, { label: 'Student Wellbeing', url: 'https://www.manchester.ac.uk/study/experience/student-support/', desc: 'Mental health support' }] },
  { keys: ['birmingham'], name: 'University of Birmingham', city: 'Birmingham', fact: 'Birmingham has a stunning redbrick campus and is one of the most diverse Russell Group universities.', links: [{ label: 'Guild of Students', url: 'https://www.guildofstudents.com', desc: 'Student union and representation' }, { label: 'Student Wellbeing', url: 'https://www.birmingham.ac.uk/university/colleges/les/student-support', desc: 'Wellbeing and counselling' }] },
  { keys: ['leeds'], name: 'University of Leeds', city: 'Leeds', fact: 'Leeds is a top research university in one of the most loved student cities in the UK.', links: [{ label: 'Leeds University Union', url: 'https://www.luu.org.uk', desc: 'Student union and peer support' }, { label: 'Student Wellbeing', url: 'https://students.leeds.ac.uk/wellbeing', desc: 'Counselling and mental health' }] },
  { keys: ['sheffield'], name: 'University of Sheffield', city: 'Sheffield', fact: 'Sheffield has been voted best student city in the UK so many times it has basically stopped counting.', links: [{ label: 'Sheffield Students Union', url: 'https://www.sheffieldstudentsunion.com', desc: 'Award winning student union' }, { label: 'Student Wellbeing', url: 'https://www.sheffield.ac.uk/wellbeing', desc: 'Mental health and counselling' }] },
  { keys: ['bristol'], name: 'University of Bristol', city: 'Bristol', fact: 'Bristol is one of the most beautiful university cities in the UK.', links: [{ label: 'Bristol Students Union', url: 'https://www.bristolsu.org.uk', desc: 'Student union and support' }, { label: 'Student Wellbeing', url: 'https://www.bristol.ac.uk/students/support/wellbeing/', desc: 'Counselling and mental health' }] },
  { keys: ['edinburgh'], name: 'University of Edinburgh', city: 'Edinburgh', fact: "Edinburgh is one of the world's truly great universities in one of the most beautiful cities in Europe.", links: [{ label: 'Edinburgh University Students Association', url: 'https://www.eusa.ed.ac.uk', desc: 'Student union and support' }, { label: 'Student Wellbeing', url: 'https://www.ed.ac.uk/students/health-wellbeing/wellbeing-services', desc: 'Counselling and mental health' }] },
  { keys: ['warwick'], name: 'University of Warwick', city: 'Coventry', fact: 'Warwick is one of the fastest rising universities in the world.', links: [{ label: 'Warwick Students Union', url: 'https://www.warwicksu.com', desc: 'Student union and support' }, { label: 'Student Wellbeing', url: 'https://warwick.ac.uk/services/wss/', desc: 'Counselling and mental health' }] },
  { keys: ['nottingham'], name: 'University of Nottingham', city: 'Nottingham', fact: 'Nottingham has one of the most beautiful university campuses in the UK.', links: [{ label: 'Nottingham Students Union', url: 'https://su.nottingham.ac.uk', desc: 'Student union and welfare' }, { label: 'Student Wellbeing', url: 'https://www.nottingham.ac.uk/currentstudents/wellbeing/', desc: 'Mental health and counselling' }] },
  { keys: ['southampton'], name: 'University of Southampton', city: 'Southampton', fact: 'Southampton is a world leader in ocean science and engineering.', links: [{ label: 'Southampton Students Union', url: 'https://www.susu.org', desc: 'Student union and support' }, { label: 'Student Wellbeing', url: 'https://www.southampton.ac.uk/student-life/support/wellbeing.page', desc: 'Counselling and mental health' }] },
  { keys: ['glasgow'], name: 'University of Glasgow', city: 'Glasgow', fact: 'Glasgow is the fourth oldest university in the English speaking world.', links: [{ label: 'Glasgow University SRC', url: 'https://www.glasgowstudent.net', desc: 'Student representative council' }, { label: 'Student Wellbeing', url: 'https://www.gla.ac.uk/myglasgow/students/health/', desc: 'Counselling and mental health' }] },
  { keys: ['exeter'], name: 'University of Exeter', city: 'Exeter', fact: 'Exeter has risen dramatically in the rankings and now sits among the top UK universities.', links: [{ label: 'Exeter Students Guild', url: 'https://www.exeterguild.org', desc: 'Student union and support' }, { label: 'Student Wellbeing', url: 'https://www.exeter.ac.uk/students/wellbeing/', desc: 'Counselling and mental health' }] },
  { keys: ['durham'], name: 'Durham University', city: 'Durham', fact: 'Durham is one of the oldest and most prestigious universities in the UK.', links: [{ label: 'Durham Students Union', url: 'https://www.durhamsu.com', desc: 'Student union and support' }, { label: 'Student Wellbeing', url: 'https://www.dur.ac.uk/wellbeing/', desc: 'Counselling and mental health' }] },
  { keys: ['bath'], name: 'University of Bath', city: 'Bath', fact: 'Bath consistently tops the league tables for student satisfaction and graduate employment.', links: [{ label: 'Bath Students Union', url: 'https://www.thesubath.com', desc: 'Student union and welfare' }, { label: 'Student Wellbeing', url: 'https://www.bath.ac.uk/campaigns/wellbeing-at-bath/', desc: 'Mental health and counselling' }] },
  { keys: ['leicester'], name: 'University of Leicester', city: 'Leicester', fact: 'Leicester is a welcoming diverse university in one of the most multicultural cities in the UK.', links: [{ label: 'Leicester Students Union', url: 'https://www.leicesterunion.com', desc: 'Student union and support' }, { label: 'Student Wellbeing', url: 'https://le.ac.uk/student-support/wellbeing', desc: 'Mental health and counselling' }] },
  { keys: ['cardiff'], name: 'Cardiff University', city: 'Cardiff', fact: 'Cardiff is a Russell Group university in the capital of Wales.', links: [{ label: 'Cardiff Students Union', url: 'https://www.cardiffstudents.com', desc: 'Student union and support' }, { label: 'Student Wellbeing', url: 'https://www.cardiff.ac.uk/students/your-wellbeing', desc: 'Mental health and counselling' }] },
  { keys: ['sussex'], name: 'University of Sussex', city: 'Brighton', fact: 'Sussex is a progressive creative university on the edge of Brighton.', links: [{ label: 'Sussex Students Union', url: 'https://sussexstudent.com', desc: 'Student union and wellbeing' }, { label: 'Student Wellbeing', url: 'https://www.sussex.ac.uk/studentlife/healthandwellbeing/', desc: 'Mental health and counselling' }] },
  { keys: ['york'], name: 'University of York', city: 'York', fact: 'York has a beautiful lake campus and consistently excellent student satisfaction.', links: [{ label: 'York Students Union', url: 'https://www.yusu.org', desc: 'Student union and advice' }, { label: 'Student Wellbeing', url: 'https://www.york.ac.uk/students/health/wellbeing/', desc: 'Mental health and counselling' }] },
  { keys: ['liverpool'], name: 'University of Liverpool', city: 'Liverpool', fact: 'Liverpool is a Russell Group university in one of the most characterful cities in the UK.', links: [{ label: 'Liverpool Guild of Students', url: 'https://www.liverpoolguild.org', desc: 'Student union and support' }, { label: 'Student Wellbeing', url: 'https://www.liverpool.ac.uk/studentsupport/mentalhealth/', desc: 'Mental health and counselling' }] },
  { keys: ['newcastle'], name: 'Newcastle University', city: 'Newcastle', fact: 'Newcastle is a Russell Group university in one of the friendliest cities in the UK.', links: [{ label: 'Newcastle Students Union', url: 'https://www.nusu.co.uk', desc: 'Student union and advice' }, { label: 'Student Wellbeing', url: 'https://www.ncl.ac.uk/wellbeing/', desc: 'Mental health and counselling' }] },
  { keys: ['lancaster'], name: 'Lancaster University', city: 'Lancaster', fact: 'Lancaster is consistently ranked in the UK top 10 and top 150 in the world.', links: [{ label: 'Lancaster Students Union', url: 'https://www.lancastersu.co.uk', desc: 'Student union and welfare' }, { label: 'Student Wellbeing', url: 'https://www.lancaster.ac.uk/wec/', desc: 'Mental health and counselling' }] },
  { keys: ['st andrews','saint andrews'], name: 'University of St Andrews', city: 'St Andrews', fact: "St Andrews is Scotland's oldest university and one of the most beautiful places to study.", links: [{ label: 'Students Association', url: 'https://www.yourunion.net', desc: 'Student union and wellbeing' }, { label: 'Student Wellbeing', url: 'https://www.st-andrews.ac.uk/students/advice/wellbeing/', desc: 'Mental health and counselling' }] },
  { keys: ['coventry'], name: 'Coventry University', city: 'Coventry', fact: 'Coventry is one of the most innovative modern universities in the UK.', links: [{ label: 'Coventry Students Union', url: 'https://www.coventryunion.com', desc: 'Student union and support' }, { label: 'Student Wellbeing', url: 'https://www.coventry.ac.uk/life-on-campus/health-and-wellbeing/', desc: 'Mental health and counselling' }] },
  { keys: ['middlesex','mdx'], name: 'Middlesex University London', city: 'London', fact: 'Middlesex has one of the most diverse student communities in the UK.', links: [{ label: 'Middlesex Students Union', url: 'https://www.mdxsu.com', desc: 'Student union and support' }, { label: 'Student Wellbeing', url: 'https://www.mdx.ac.uk/student-life/student-wellbeing', desc: 'Mental health and counselling' }] },
  { keys: ['queen mary','qmul'], name: 'Queen Mary University of London', city: 'London', fact: 'Queen Mary has one of the most diverse student populations of any university in the UK.', links: [{ label: 'QMSU', url: 'https://www.qmsu.org', desc: 'Student union and support' }, { label: 'Student Wellbeing', url: 'https://www.qmul.ac.uk/students/wellbeing/', desc: 'Mental health and counselling' }] },
  { keys: ['hertfordshire'], name: 'University of Hertfordshire', city: 'Hatfield', fact: 'Hertfordshire has one of the highest rates of graduate employment in the UK.', links: [{ label: 'Hertfordshire Students Union', url: 'https://www.hertfordshireunion.com', desc: 'Student union and support' }, { label: 'Student Wellbeing', url: 'https://www.herts.ac.uk/life/student-support/wellbeing', desc: 'Mental health and counselling' }] },
  { keys: ['portsmouth'], name: 'University of Portsmouth', city: 'Portsmouth', fact: 'Portsmouth is a modern university in a vibrant coastal city.', links: [{ label: 'Portsmouth Students Union', url: 'https://www.upsu.net', desc: 'Student union and support' }, { label: 'Student Wellbeing', url: 'https://www.port.ac.uk/student-life/health-and-wellbeing', desc: 'Mental health and counselling' }] },
  { keys: ['huddersfield'], name: 'University of Huddersfield', city: 'Huddersfield', fact: 'Huddersfield won Times Higher Education University of the Year.', links: [{ label: 'Huddersfield Students Union', url: 'https://www.huddersfieldstudentu.com', desc: 'Student union and support' }, { label: 'Student Wellbeing', url: 'https://students.hud.ac.uk/healthwellbeing/', desc: 'Mental health and counselling' }] },
  { keys: ['strathclyde'], name: 'University of Strathclyde', city: 'Glasgow', fact: 'Strathclyde was named Times Higher Education University of the Year in 2019.', links: [{ label: 'Strathclyde Students Association', url: 'https://www.strathunion.com', desc: 'Student union and support' }, { label: 'Student Wellbeing', url: 'https://www.strath.ac.uk/studywithus/lifeatstrathclyde/wellbeing/', desc: 'Mental health and counselling' }] },
  { keys: ['reading'], name: 'University of Reading', city: 'Reading', fact: 'Reading is only 25 minutes from London by train with a beautiful green campus.', links: [{ label: 'Reading Students Union', url: 'https://www.rusu.co.uk', desc: 'Student union and wellbeing' }, { label: 'Student Wellbeing', url: 'https://www.reading.ac.uk/essentials/health-and-wellbeing', desc: 'Mental health and counselling' }] },
  { keys: ['brunel'], name: 'Brunel University London', city: 'London', fact: 'Brunel has a strong reputation for engineering, design and sport.', links: [{ label: 'Brunel Students Union', url: 'https://www.brunelstudentsunion.com', desc: 'Student union and support' }, { label: 'Student Wellbeing', url: 'https://www.brunel.ac.uk/life/student-support/wellbeing', desc: 'Mental health and counselling' }] },
  { keys: ['city university','city london'], name: 'City, University of London', city: 'London', fact: 'City sits right in the heart of London at the edge of the financial district.', links: [{ label: 'City Students Union', url: 'https://www.culsu.co.uk', desc: 'Student union and support' }, { label: 'Student Wellbeing', url: 'https://www.city.ac.uk/current-students/health-wellbeing-sport', desc: 'Mental health and counselling' }] },
  { keys: ['east london','uel'], name: 'University of East London', city: 'London', fact: 'UEL has a wonderfully diverse community driven atmosphere in East London.', links: [{ label: 'UEL Students Union', url: 'https://www.uelsu.net', desc: 'Student union and support' }, { label: 'Student Wellbeing', url: 'https://www.uel.ac.uk/students/wellbeing', desc: 'Mental health and counselling' }] },
  { keys: ['roehampton'], name: 'University of Roehampton', city: 'London', fact: 'Roehampton has a beautiful campus in South West London surrounded by parkland.', links: [{ label: 'Roehampton Students Union', url: 'https://www.roehamptonstudentsunion.com', desc: 'Student union and support' }, { label: 'Student Wellbeing', url: 'https://www.roehampton.ac.uk/student-life/wellbeing/', desc: 'Mental health and counselling' }] },
  { keys: ['greenwich'], name: 'University of Greenwich', city: 'London', fact: 'Greenwich has one of the most spectacular campus settings of any university in the world.', links: [{ label: 'Greenwich Students Union', url: 'https://www.greenwichsu.co.uk', desc: 'Student union and support' }, { label: 'Student Wellbeing', url: 'https://www.gre.ac.uk/student-wellbeing', desc: 'Mental health and counselling' }] },
  { keys: ['essex'], name: 'University of Essex', city: 'Colchester', fact: 'Essex is one of the top universities in Europe for politics, sociology and economics.', links: [{ label: 'Essex Students Union', url: 'https://www.essexstudent.com', desc: 'Student union and support' }, { label: 'Student Wellbeing', url: 'https://www.essex.ac.uk/student/professional-services/student-wellbeing-and-inclusivity-team', desc: 'Mental health and counselling' }] },
  { keys: ['kent'], name: 'University of Kent', city: 'Canterbury', fact: 'Kent is based in Canterbury and has a wonderfully international feel.', links: [{ label: 'Kent Union', url: 'https://www.kentunion.co.uk', desc: 'Student union and advice' }, { label: 'Student Wellbeing', url: 'https://student.kent.ac.uk/support/wellbeing', desc: 'Counselling and mental health' }] },
];

const countries = [
  { key: 'nepal', flag: '🇳🇵', fact: 'Nepal is an absolutely stunning country sitting right in the heart of the Himalayas with Mount Everest towering above everything else.', embassy: { name: 'Embassy of Nepal, London', url: 'https://nepembassy.org.uk' }, orgs: [{ name: 'NRN UK', url: 'https://nrnuk.com' }, { name: 'IRN Nepal UK', url: 'https://irnnepal.org' }] },
  { key: 'india', flag: '🇮🇳', fact: 'India is one of the most extraordinary countries in the world with ancient history and incredible diversity.', embassy: { name: 'High Commission of India, London', url: 'https://hciuk.gov.in' }, orgs: [{ name: 'NISAU UK', url: 'https://nisauuk.org' }] },
  { key: 'pakistan', flag: '🇵🇰', fact: 'Pakistan is a country of breathtaking diversity from the deserts of Sindh to the peaks of K2.', embassy: { name: 'Pakistan High Commission, London', url: 'https://www.phclondon.org' }, orgs: [{ name: 'British Pakistan Foundation', url: 'https://bpfoundation.org.uk' }] },
  { key: 'bangladesh', flag: '🇧🇩', fact: 'Bangladesh is a country of rivers, green landscapes and incredibly warm people.', embassy: { name: 'Bangladesh High Commission, London', url: 'https://bhclondon.org.uk' }, orgs: [{ name: 'British Bangladesh Chamber', url: 'https://bbcc.org.uk' }] },
  { key: 'sri lanka', flag: '🇱🇰', fact: 'Sri Lanka is often called the Pearl of the Indian Ocean with ancient temples and golden beaches.', embassy: { name: 'Sri Lanka High Commission, London', url: 'https://slhclondon.org' }, orgs: [{ name: 'Sri Lanka UK Community', url: 'https://srilankauk.com' }] },
  { key: 'china', flag: '🇨🇳', fact: 'China is one of the oldest continuing civilisations on earth with over five thousand years of history.', embassy: { name: 'Chinese Embassy, London', url: 'https://www.chinese-embassy.org.uk' }, orgs: [{ name: 'CSSA UK', url: 'https://cssauk.org.uk' }] },
  { key: 'japan', flag: '🇯🇵', fact: 'Japan is a place unlike anywhere else where ancient temples sit next to bullet trains.', embassy: { name: 'Embassy of Japan, London', url: 'https://www.uk.emb-japan.go.jp' }, orgs: [{ name: 'Japan Society UK', url: 'https://www.japansociety.org.uk' }] },
  { key: 'south korea', flag: '🇰🇷', fact: 'South Korea has become a global leader in technology, film, music and food all at once.', embassy: { name: 'Korean Embassy, London', url: 'https://overseas.mofa.go.kr/gb-en/index.do' }, orgs: [{ name: 'Korean Students Association UK', url: 'https://www.ksauk.co.uk' }] },
  { key: 'malaysia', flag: '🇲🇾', fact: 'Malaysia is one of the most wonderfully diverse countries in Southeast Asia.', embassy: { name: 'Malaysian High Commission, London', url: 'https://www.kln.gov.my/web/gbr_london' }, orgs: [{ name: 'Malaysian Student Department UK', url: 'https://www.msd.org.uk' }] },
  { key: 'indonesia', flag: '🇮🇩', fact: 'Indonesia is the largest archipelago nation in the world with over seventeen thousand islands.', embassy: { name: 'Indonesian Embassy, London', url: 'https://kemlu.go.id/london/en' }, orgs: [{ name: 'PPI UK', url: 'https://ppiuk.org' }] },
  { key: 'thailand', flag: '🇹🇭', fact: 'Thailand is known as the Land of Smiles and the warmth of Thai people really lives up to that name.', embassy: { name: 'Royal Thai Embassy, London', url: 'https://thaiembassyuk.org.uk' }, orgs: [{ name: 'Thai Society UK', url: 'https://thaisocietyuk.org' }] },
  { key: 'vietnam', flag: '🇻🇳', fact: 'Vietnam has emerged with its culture, food and spirit completely intact after so much.', embassy: { name: 'Embassy of Vietnam, London', url: 'https://vnembassy-london.mofa.gov.vn' }, orgs: [{ name: 'Vietnamese Community UK', url: 'https://www.vietnamesecommunity.co.uk' }] },
  { key: 'philippines', flag: '🇵🇭', fact: 'The Philippines is an archipelago of over seven thousand islands and one of the most joyful cultures in Asia.', embassy: { name: 'Philippine Embassy, London', url: 'https://londonpe.dfa.gov.ph' }, orgs: [{ name: 'Filipino Community UK', url: 'https://www.filipinocommunity.co.uk' }] },
  { key: 'nigeria', flag: '🇳🇬', fact: 'Nigeria is the giant of Africa and one of its most culturally rich nations.', embassy: { name: 'Nigerian High Commission, London', url: 'https://www.nigeriahc.org.uk' }, orgs: [{ name: 'NUNS UK', url: 'https://nunsgb.com' }] },
  { key: 'ghana', flag: '🇬🇭', fact: 'Ghana was the first country in sub Saharan Africa to gain independence and has always held that pioneering spirit.', embassy: { name: 'Ghana High Commission, London', url: 'https://ghc.org.uk' }, orgs: [{ name: 'Ghana Union UK', url: 'https://www.ghanaunionuk.org' }] },
  { key: 'kenya', flag: '🇰🇪', fact: 'Kenya is one of the most beautiful countries in the world with the Maasai Mara and incredible wildlife.', embassy: { name: 'Kenya High Commission, London', url: 'https://kenyahighcommission.co.uk' }, orgs: [{ name: 'Kenyan Community Abroad UK', url: 'https://kenyancommunityabroad.org' }] },
  { key: 'ethiopia', flag: '🇪🇹', fact: 'Ethiopia is one of the oldest nations on earth and the birthplace of coffee.', embassy: { name: 'Ethiopian Embassy, London', url: 'https://www.ethioembassy.org.uk' }, orgs: [{ name: 'Ethiopian Community UK', url: 'https://www.ethiopiancommunity.co.uk' }] },
  { key: 'south africa', flag: '🇿🇦', fact: 'South Africa is the Rainbow Nation that went through one of the most remarkable peaceful transitions in history.', embassy: { name: 'South Africa High Commission, London', url: 'https://www.southafricahouseuk.com' }, orgs: [{ name: 'South African Community UK', url: 'https://www.sacommunity.co.uk' }] },
  { key: 'zimbabwe', flag: '🇿🇼', fact: 'Zimbabwe is home to Victoria Falls one of the most spectacular natural wonders on earth.', embassy: { name: 'Zimbabwe Embassy, London', url: 'https://www.zimbabweembassy.org.uk' }, orgs: [{ name: 'Zimbabwe Community UK', url: 'https://www.zimbabwecommunity.co.uk' }] },
  { key: 'uganda', flag: '🇺🇬', fact: 'Uganda is called the Pearl of Africa and is home to mountain gorillas and the source of the Nile.', embassy: { name: 'Uganda High Commission, London', url: 'https://www.ugandahighcommission.co.uk' }, orgs: [{ name: 'Uganda Community UK', url: 'https://www.ugandacommunity.org.uk' }] },
  { key: 'cameroon', flag: '🇨🇲', fact: 'Cameroon is often called Africa in miniature because it has almost every landscape the continent offers.', embassy: { name: 'Cameroon High Commission, London', url: 'https://www.cameroonhighcommission.co.uk' }, orgs: [{ name: 'Cameroon Community UK', url: 'https://camerooncommunityuk.org' }] },
  { key: 'tanzania', flag: '🇹🇿', fact: 'Tanzania is home to Kilimanjaro, the Serengeti, Zanzibar and the Ngorongoro Crater.', embassy: { name: 'Tanzania High Commission, London', url: 'https://www.tanzania-gov.uk' }, orgs: [{ name: 'Tanzanian Community UK', url: 'https://tanzaniancommunityuk.org' }] },
  { key: 'sierra leone', flag: '🇸🇱', fact: 'Sierra Leone is a country that has shown the world what resilience truly looks like.', embassy: { name: 'Sierra Leone High Commission, London', url: 'https://www.slhc-uk.org.uk' }, orgs: [{ name: 'Sierra Leone Community UK', url: 'https://slcommunityuk.org' }] },
  { key: 'saudi arabia', flag: '🇸🇦', fact: 'Saudi Arabia is home to the holy cities of Mecca and Medina and people known for extraordinary hospitality.', embassy: { name: 'Royal Embassy of Saudi Arabia, London', url: 'https://www.saudiembassy.org.uk' }, orgs: [{ name: 'Saudi Students Club UK', url: 'https://www.sscuk.org' }] },
  { key: 'uae', flag: '🇦🇪', fact: 'The UAE has transformed itself into one of the most modern and cosmopolitan places on earth.', embassy: { name: 'UAE Embassy, London', url: 'https://www.uaeembassyuk.net' }, orgs: [{ name: 'UAE Students UK', url: 'https://uaestudentsuk.com' }] },
  { key: 'jordan', flag: '🇯🇴', fact: 'Jordan is home to Petra, one of the wonders of the ancient world, and the Dead Sea.', embassy: { name: 'Embassy of Jordan, London', url: 'https://www.jordanembassy.org.uk' }, orgs: [{ name: 'Jordanian Community UK', url: 'https://jordaniancommunityuk.org' }] },
  { key: 'iran', flag: '🇮🇷', fact: 'Iran is one of the cradles of human civilisation and the poetry of Rumi still moves people today.', embassy: { name: 'Embassy of Iran, London', url: 'https://iran-embassy.org.uk' }, orgs: [{ name: 'Iranian Community UK', url: 'https://iranianuk.com' }] },
  { key: 'germany', flag: '🇩🇪', fact: 'Germany is a powerhouse of culture, engineering and ideas.', embassy: { name: 'German Embassy, London', url: 'https://london.diplo.de' }, orgs: [{ name: 'German British Forum', url: 'https://www.german-british-forum.org.uk' }] },
  { key: 'france', flag: '🇫🇷', fact: 'France is one of the most culturally significant countries in the world in art, cuisine and philosophy.', embassy: { name: 'French Embassy, London', url: 'https://uk.ambafrance.org' }, orgs: [{ name: 'French Community UK', url: 'https://frenchcommunity.co.uk' }] },
  { key: 'italy', flag: '🇮🇹', fact: 'Italy gave the world the Renaissance, pizza, pasta, opera and Ferrari.', embassy: { name: 'Italian Embassy, London', url: 'https://ambrlondra.esteri.it' }, orgs: [{ name: 'Italian Community UK', url: 'https://italians-uk.com' }] },
  { key: 'spain', flag: '🇪🇸', fact: 'Spain is one of the most joyful and passionate countries in Europe.', embassy: { name: 'Spanish Embassy, London', url: 'https://www.exteriores.gob.es/embajadas/londres' }, orgs: [{ name: 'Spanish Community UK', url: 'https://spanishcommunityuk.com' }] },
  { key: 'usa', flag: '🇺🇸', fact: 'The United States is one of the most culturally influential nations in the world.', embassy: { name: 'US Embassy, London', url: 'https://uk.usembassy.gov' }, orgs: [{ name: 'Democrats Abroad UK', url: 'https://www.democratsabroad.org/uk' }] },
  { key: 'canada', flag: '🇨🇦', fact: 'Canada is one of the most admired countries in the world with vast natural landscapes and inclusive values.', embassy: { name: 'Canadian High Commission, London', url: 'https://www.canada.ca/en/high-commission/united-kingdom.html' }, orgs: [{ name: 'Canadian Association UK', url: 'https://canadianassociation.co.uk' }] },
  { key: 'brazil', flag: '🇧🇷', fact: 'Brazil is the most vibrant country in South America with the Amazon, Carnival and incredible football.', embassy: { name: 'Brazilian Embassy, London', url: 'https://londrina.itamaraty.gov.br' }, orgs: [{ name: 'Brazilian Community UK', url: 'https://braziliansinuk.com' }] },
  { key: 'australia', flag: '🇦🇺', fact: 'Australia is a vast and beautiful country known for its stunning landscapes, wildlife and laid back culture.', embassy: { name: 'Australian High Commission, London', url: 'https://uk.embassy.gov.au' }, orgs: [{ name: 'Australia UK Chamber', url: 'https://www.aukc.org.uk' }] },
  { key: 'new zealand', flag: '🇳🇿', fact: 'New Zealand is one of the most naturally beautiful countries on earth.', embassy: { name: 'New Zealand High Commission, London', url: 'https://www.mfat.govt.nz/en/countries-and-regions/europe/united-kingdom/' }, orgs: [{ name: 'New Zealand Society UK', url: 'https://nzsocietyuk.org' }] },
  { key: 'mexico', flag: '🇲🇽', fact: 'Mexico has one of the richest cultural heritages in the world with ancient civilisations and vibrant traditions.', embassy: { name: 'Mexican Embassy, London', url: 'https://embamex.sre.gob.mx/reinounido' }, orgs: [{ name: 'Mexican Community UK', url: 'https://mexicancommunityuk.org' }] },
  { key: 'colombia', flag: '🇨🇴', fact: 'Colombia is a country of incredible natural diversity, warm people and rich culture.', embassy: { name: 'Colombian Embassy, London', url: 'https://reinounido.embajada.gov.co' }, orgs: [{ name: 'Colombian Community UK', url: 'https://colombiancommunityuk.org' }] },
  { key: 'peru', flag: '🇵🇪', fact: 'Peru is home to Machu Picchu and one of the most ancient civilisations in the world.', embassy: { name: 'Peruvian Embassy, London', url: 'https://www.embajada-peruuk.com' }, orgs: [{ name: 'Peruvian Community UK', url: 'https://peruviancommunityuk.org' }] },
  { key: 'argentina', flag: '🇦🇷', fact: 'Argentina is a passionate nation known for tango, football, incredible landscapes and world class food.', embassy: { name: 'Argentine Embassy, London', url: 'https://www.argentine-embassy-uk.org' }, orgs: [{ name: 'Argentine Community UK', url: 'https://argentinecommunityuk.org' }] },
  { key: 'egypt', flag: '🇪🇬', fact: 'Egypt is one of the oldest civilisations in human history home to the pyramids and the Nile.', embassy: { name: 'Egyptian Embassy, London', url: 'https://www.egyptembassy.net' }, orgs: [{ name: 'Egyptian Community UK', url: 'https://egyptiancommunityuk.org' }] },
  { key: 'morocco', flag: '🇲🇦', fact: 'Morocco is a fascinating blend of Arab, Berber and European cultures with stunning landscapes.', embassy: { name: 'Moroccan Embassy, London', url: 'https://www.moroccanembassylondon.org.uk' }, orgs: [{ name: 'Moroccan Community UK', url: 'https://moroccancommunityuk.org' }] },
  { key: 'turkey', flag: '🇹🇷', fact: 'Turkey bridges Europe and Asia and has one of the richest cultural heritages in the world.', embassy: { name: 'Turkish Embassy, London', url: 'https://london.emb.mfa.gov.tr' }, orgs: [{ name: 'Turkish Community UK', url: 'https://www.turkishcommunity.co.uk' }] },
  { key: 'greece', flag: '🇬🇷', fact: 'Greece is the birthplace of democracy, philosophy and the Olympic Games.', embassy: { name: 'Greek Embassy, London', url: 'https://www.mfa.gr/uk/en/' }, orgs: [{ name: 'Greek Community UK', url: 'https://greekcommunityuk.org' }] },
  { key: 'poland', flag: '🇵🇱', fact: 'Poland has one of the fastest growing economies in Europe and a proud cultural heritage.', embassy: { name: 'Polish Embassy, London', url: 'https://www.gov.pl/web/unitedkingdom' }, orgs: [{ name: 'Polish Community UK', url: 'https://www.polishcommunity.co.uk' }] },
  { key: 'romania', flag: '🇷🇴', fact: 'Romania has stunning landscapes, medieval castles and one of the fastest growing tech sectors in Europe.', embassy: { name: 'Romanian Embassy, London', url: 'https://londra.mae.ro' }, orgs: [{ name: 'Romanian Community UK', url: 'https://romaniancommunityuk.org' }] },
  { key: 'ukraine', flag: '🇺🇦', fact: 'Ukraine has a rich cultural heritage and a deeply resilient and proud population.', embassy: { name: 'Ukrainian Embassy, London', url: 'https://uk.mfa.gov.ua/en' }, orgs: [{ name: 'Ukrainian Community UK', url: 'https://www.augb.co.uk' }] },
  { key: 'russia', flag: '🇷🇺', fact: 'Russia is the largest country in the world spanning eleven time zones with a rich cultural heritage.', embassy: { name: 'Russian Embassy, London', url: 'https://www.rusemb.org.uk' }, orgs: [{ name: 'Russian Community UK', url: 'https://russiancommunityuk.org' }] },
  { key: 'kazakhstan', flag: '🇰🇿', fact: 'Kazakhstan is the ninth largest country in the world with a fascinating nomadic heritage.', embassy: { name: 'Embassy of Kazakhstan, London', url: 'https://www.kazembassy.org.uk' }, orgs: [{ name: 'Kazakh Community UK', url: 'https://kazakhcommunityuk.org' }] },
  { key: 'uzbekistan', flag: '🇺🇿', fact: 'Uzbekistan sits at the heart of the ancient Silk Road with cities like Samarkand and Bukhara.', embassy: { name: 'Embassy of Uzbekistan, London', url: 'https://uzbekembassy.org' }, orgs: [{ name: 'Uzbek Community UK', url: 'https://uzbekcommunity.co.uk' }] },
  { key: 'united kingdom', flag: '🇬🇧', fact: 'The UK is home to some of the best universities in the world and an incredibly multicultural society.', embassy: { name: 'Student Finance England', url: 'https://www.gov.uk/student-finance' }, orgs: [{ name: 'Citizens Advice', url: 'https://www.citizensadvice.org.uk' }, { name: 'Turn2Us', url: 'https://www.turn2us.org.uk' }] },
  { key: 'england', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', fact: 'England is home to some of the finest universities in the world.', embassy: { name: 'Student Finance England', url: 'https://www.gov.uk/student-finance' }, orgs: [{ name: 'Citizens Advice', url: 'https://www.citizensadvice.org.uk' }] },
  { key: 'scotland', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', fact: 'Scotland has world class universities and Scottish students benefit from free tuition.', embassy: { name: 'Student Awards Agency Scotland', url: 'https://www.saas.gov.uk' }, orgs: [{ name: 'Citizens Advice Scotland', url: 'https://www.cas.org.uk' }] },
  { key: 'wales', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', fact: 'Wales is a beautiful bilingual nation with a strong sense of identity and great universities.', embassy: { name: 'Student Finance Wales', url: 'https://www.studentfinancewales.co.uk' }, orgs: [{ name: 'Citizens Advice Wales', url: 'https://www.citizensadvice.org.uk/wales/' }] },
];

async function seed() {
  await connectDB();

  console.log('Clearing existing data...');
  await University.deleteMany({});
  await Country.deleteMany({});

  console.log('Seeding universities...');
  await University.insertMany(universities);
  console.log(`Inserted ${universities.length} universities`);

  console.log('Seeding countries...');
  await Country.insertMany(countries);
  console.log(`Inserted ${countries.length} countries`);

  console.log('Done!');
  process.exit(0);
}

seed().catch(err => {
  console.error(err);
  process.exit(1);
});